name: BaekjoonHub to Blog
on:
  push:
    paths:
      - '**/README.md'
      - '**/*.cpp'
      - '**/*.java'
      - '**/*.py'

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
      # 1. BaekjoonHub Repository Checkout
      - name: Checkout BaekjoonHub Repository
        uses: actions/checkout@v2
        with:
          repository: 'sms1875/CodingTestStudy'
          path: 'BaekjoonHub'

      # 2. Create Blog Post Format and _posts Directory
      - name: Create Blog Post Format
        run: |
          echo "Creating _posts directory..."
          mkdir -p ./BaekjoonHub/_posts
          echo "Generating blog posts from newly added problems..."
          # 이 부분에서 README.md 파일을 _posts 폴더에 복사 또는 생성하는 로직 추가
          # 예를 들어, 모든 README.md 파일을 _posts 폴더로 복사
          find ./BaekjoonHub -name "README.md" -exec cp {} ./BaekjoonHub/_posts/ \;

      # 3. Checkout Chirpy Blog Repository
      - name: Checkout Chirpy Blog Repository
        uses: actions/checkout@v2
        with:
          repository: 'sms1875/sms1875.github.io'
          path: 'ChirpyBlog'
          token: ${{ secrets.ACCESS_TOKEN }}  # 권한 설정 (GitHub Secrets 활용)

      # 4. Copy Generated Files to Chirpy Blog Repository
      - name: Move Generated Files to Blog
        run: |
          echo "Copying generated blog posts to Chirpy blog repository..."
          cp -R ./BaekjoonHub/_posts/* ./ChirpyBlog/_posts/

      # 5. Commit and Push to Chirpy Blog Repository
      - name: Commit and Push to Chirpy Blog
        working-directory: ChirpyBlog
        run: |
          git config user.name "sms1875[bot]"
          git config user.email "sms1875@gmail.com"
          git add .
          git commit -m "Add new problem posts from BaekjoonHub"
          git push origin main
